language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer install --prefer-source --dev

script: ./demeanor --all --no-coverage

maxtrix:
    allowed_failures:
        - php: hhvm
    fast_finish: true
